isqrt:
visiting 0
visiting 7
visiting 9
visiting 11
visiting 13
visiting 16
visiting 16
visiting 23
visiting 26
0: %rdx
2: %r9
3: %r8
4: %rdi
5: %rsi
6: %rdx
7: %rdx
9: %rdx
10: %rbx
12: %rdx
15: %rdx
16: %rdx
17: %rdx
20: %rdx
21: %rbx
22: %rbx
23: %rbx
24: %rdx
26: %rdx
27: %rdx
29: %rdx
main:
visiting 0
0: %rdx
3: %rdi
4: %rsi
5: %rbx
6: %rdx
7: %rdx
8: %rdx
9: %rdx
10: %rdx
1: %rdx
