@1 = global [921 x i8] c"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tempus viverra est, in posuere justo porttitor sit amet. Duis vitae nulla eget neque cursus vulputate id vel leo. Nulla et pellentesque nulla. Etiam sed vulputate risus. Sed tempus varius est, quis sollicitudin lectus semper tempus. Fusce a ante egestas, fringilla purus mollis, volutpat neque. Ut eget nisi ut turpis ullamcorper lacinia. Pellentesque volutpat ultrices massa in sagittis. Integer aliquam vel ligula vitae pellentesque. Sed ut neque aliquet, rhoncus ex sit amet, tristique erat. Nullam porta, mauris vel tincidunt porta, eros ex sagittis lectus, gravida ultricies lorem ipsum eget nisl. Vivamus commodo velit convallis velit luctus, eu luctus leo suscipit. Pellentesque tellus leo, feugiat vel feugiat id, viverra a tellus. Fusce vitae malesuada nibh, a aliquam magna. Curabitur tortor ligula, sollicitudin vel sodales sed, gravida eu turpis.\0A\0A\00"
@2 = global [723 x i8] c"Duis malesuada erat et leo ultrices vestibulum. Pellentesque nec viverra nisi, eu viverra tortor. Curabitur facilisis blandit leo in aliquam. Proin mattis ultricies euismod. Proin vehicula nulla velit, a viverra leo aliquet at. Mauris ornare sit amet odio id vestibulum. Nulla blandit pretium ipsum, accumsan pharetra augue scelerisque at. Morbi lobortis leo at cursus fermentum. Cras eget ultrices orci. Integer convallis ante erat, et bibendum dui luctus ac. Duis convallis a lectus feugiat ullamcorper. Etiam blandit, leo at gravida viverra, urna diam hendrerit massa, at vestibulum magna nunc sed ex. Aenean interdum dolor sit amet rhoncus commodo. Maecenas bibendum placerat risus, quis ullamcorper quam rutrum non.\0A\0A\00"
@3 = global [906 x i8] c"Pellentesque non libero pretium, efficitur tortor sit amet, sollicitudin mauris. Duis tincidunt eros et nulla volutpat vestibulum. Nullam augue purus, pulvinar non accumsan ut, condimentum quis arcu. Maecenas faucibus, erat sit amet lacinia gravida, nisl lorem sagittis ipsum, vel ultricies neque purus ac risus. Curabitur vitae dapibus erat, eu ornare sapien. Phasellus ultricies magna ut lectus tincidunt, id elementum enim commodo. Curabitur consectetur nisl a mollis aliquam. Nunc imperdiet tellus ut sagittis dictum. Morbi placerat, diam et auctor dictum, odio risus dapibus massa, eu bibendum elit nibh sed elit. Integer quis tempor odio, nec posuere ex. Suspendisse condimentum odio at erat luctus rutrum id tincidunt erat. Sed dictum est eu metus commodo, sed rhoncus enim pulvinar. Nam sit amet dapibus odio, vel vehicula arcu. Vestibulum non urna vehicula, sollicitudin nisl id, efficitur tellus.\0A\0A\00"
@4 = global [735 x i8] c"Nulla ac dolor ligula. Sed a purus imperdiet, mollis est in, porttitor neque. Praesent pulvinar nisi turpis, nec fringilla tortor varius in. Vivamus ultricies dictum rhoncus. Praesent sed lacus tortor. Proin fermentum a libero vitae cursus. Cras egestas diam nec accumsan varius. Sed ut sodales nulla. Aliquam molestie ac turpis non gravida. Sed scelerisque, erat a feugiat vulputate, dolor felis placerat urna, ac efficitur eros tortor tristique mauris. Donec pulvinar nisl quis lacus suscipit, in feugiat nisl ullamcorper. Phasellus non cursus eros. Nunc scelerisque lobortis justo at feugiat. Proin augue enim, convallis vel dui aliquet, accumsan pellentesque justo. Praesent ex sapien, viverra quis leo id, euismod pulvinar sem.\0A\0A\00"
@5 = global [567 x i8] c"Duis aliquet, elit eu porta aliquam, lectus mauris finibus arcu, at molestie justo enim sed diam. Integer sed risus eget enim sodales facilisis. Nulla facilisi. Aliquam in nisi sit amet lorem elementum mattis. In hac habitasse platea dictumst. Morbi ultricies risus non luctus convallis. Cras luctus sem ut tortor eleifend semper. Vivamus varius sit amet arcu non placerat. Morbi sed tellus semper, porta est vel, imperdiet felis. Sed tempus facilisis faucibus. Sed sed massa ante. Duis eu eleifend neque. Mauris eleifend enim lorem, eu laoreet lectus dignissim at.\0A\00"

declare i32 @printf(i8*, ...)

define i8 @main() {
  call i32 (i8*) @printf(i8* @1)
  call i32 (i8*) @printf(i8* @2)
  call i32 (i8*) @printf(i8* @3)
  call i32 (i8*) @printf(i8* @4)
  call i32 (i8*) @printf(i8* @5)
  ret i8 0
}
